### ISSUE TITLE
No content found for data science products on Azure Gov

### ISSUE THREAD

**Issue by emdata-design** [emdata-design/azure-data-science#8]
There's no content in either the README or pptx slides on availability of products on Azure Gov

Update README for Azure Gov:
- [x] Create Azure Gov section
- [x] what is the status of these products (roadmap/preview/GA)?
- [x] what is the feature parity to commercial product?
- [x] what accreditations does the product have? 

Will not update pptx slides to keep them tight and tidy

**Comment by emdata-design** [comment]
Resources that provide information on the status of the products:

Azure Machine Learning service:
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=machine-learning-service&regions=usgov-non-regional,us-dod-central,us-dod-east,usgov-arizona,usgov-iowa,usgov-texas,usgov-virginia

Azure Databricks:
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=databricks&regions=usgov-non-regional,us-dod-central,us-dod-east,usgov-arizona,usgov-iowa,usgov-texas,usgov-virginia

**Comment by emdata-design** [comment]
Blog that suggests Azure Machine Learning service is at feature parity with commercial version:
https://devblogs.microsoft.com/azuregov/azure-government-releases-40-new-services-nearing-parity-with-azure-commercial/

**Comment by emdata-design** [comment]
Docs that list the accreditations Azure Machine Learning has:
https://docs.microsoft.com/en-us/azure/azure-government/compliance/azure-services-in-fedramp-auditscope#azure-public-services-by-audit-scope

**Comment by tonmcg** [comment]
Closing issue
